tap "homebrew/cask-fonts"

brew "neovim", args: ["HEAD"]
brew "tmux"
brew "z"
brew "volta"
brew "asdf"
brew "ripgrep"
brew "httpie"
brew "gh"
brew "git"

cask "obsidian"
cask "brave-browser"
cask "google-chrome"
cask "alacritty"
cask "docker"
cask "spark"
cask "moom"
cask "launchbar"
cask "little-snitch"
cask "istat-menus"
cask "discord"
cask "spotify"
cask "slack"
cask "twist"
cask "dropbox"
cask "freedom"
cask "zotero"
cask "signal"
cask "zoom"

cask "font-fira-code"
cask "font-jetbrains-mono"
